---

version: '3.8'
services:
  db:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: myapp
      MYSQL_USER: myappuser
      MYSQL_PASSWORD: myapppass
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - db-data:/var/lib/mysql
  php:
    build: ./php
    depends_on:
    - db
    ports:
    - 8562:8000
    volumes:
    - ./work:/work

volumes:
  db-data: